var cp = require('child_process')
const { writeFileSync } = require('fs')
const { join } = require('path')
cp.execSync(`rm -rf docs `,{stdio:[0,1,2]})
cp.execSync(`npm run build`,{stdio:[0,1,2]})
cp.execSync(`npx next export`,{stdio:[0,1,2]})
cp.execSync(`cp out/community/overview.html out/community/index.html && mv out docs`)
writeFileSync(join(__dirname,'docs','CNAME'),`rescript-lang.org.cn`,'utf8')
writeFileSync(join(__dirname,'docs','.nojekyll'),``,'utf8')